# This Workflow Builds, Tests, Lints
name: CICD for Dev branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-api-linter:
    name: Lint API Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
      # Installs dependencies on the runner for API
      - name: Install linter options
        run: npm --prefix ./api install
      # Executes the linter on the API code base.
      - name: Run Linter
        run: npm --prefix ./api run lint
  run-ui-linter:
    name: Lint UI Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Installs dependencies on the runner for UI
      - name: Install linter options
        run: npm --prefix ./ui install
      # Executes the linter on the UI code base.
      - name: Run Linter
        run: npm --prefix ./ui run lint
  build-and-test-ui:
    name: Build and Test UI
    runs-on: ubuntu-latest
    needs: [run-ui-linter]

    steps:
      - uses: actions/checkout@v3
      - name: Build UI
        run: |
          docker build -t capstone-ui ./ui

      - name: Test UI
        run: |
          docker run -e CI=true capstone-ui npm run test

  build-and-test-api:
    name: Build and Test API
    runs-on: ubuntu-latest
    needs: [run-api-linter]
    steps:
      - uses: actions/checkout@v3
      - name: Build API
        run: |
          docker build -t capstone-api ./api
      - name: Test API
        run: |
          docker run -e CI=true capstone-api npm run test
